import type { Metadata } from "next";
import { Gilda_Display } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const gildDisplay = Gilda_Display({
	subsets: ["latin"],
	weight: "400",
	display: "swap",
	variable: "--font-gd",
});

const gilroy = localFont({
	src: [
		{
			path: "./fonts/Gilroy-Light.ttf",
			weight: "200",
			style: "normal",
		},
		{
			path: "./fonts/Gilroy-Regular.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "./fonts/Gilroy-Medium.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "./fonts/Gilroy-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "./fonts/Gilroy-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "./fonts/Gilroy-Heavy.ttf",
			weight: "900",
			style: "normal",
		},
	],
	variable: "--font-gilroy", // a custom CSS variable name
	display: "swap",
});

const psygen = localFont({
	src: "./fonts/PsygenDemo-AREoM.otf",
	variable: "--font-psygen",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${gilroy.variable} ${psygen.variable} ${gildDisplay.variable} mx-32 antialiased font-gilroy bg-[#000] text-white`}
			>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
